import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Providers from './providers'
import ThemeButton from './components/ThemeButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          {/* Header */}
          <header className='bg-gray-100 py-6 px-10'>
            <nav className='container flex items-center justify-between text-gray-500'>
              <ul className='flex gap-6'>
                <li>
                  <Link href='/'>Home</Link>
                </li>
                <li>
                  <Link href='/'>About</Link>
                </li>
                <li>
                  <Link href='/'>Users</Link>
                </li>
              </ul>
              <ThemeButton/>
            </nav>
          </header>
          {/* Page */}
          <main>{children}</main>

          {/* Footer */}
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
